// Generated by scripts/area-table.ts - do not edit by hand.
// Union areas of the construction, exact clipping cross-checked against grid
// sampling. The needle's naive half-disc sweep has area 1.5708;
// these are what the construction brings that down to.

export interface AreaRow {
  readonly depth: number
  /** Overlap parameter chosen by measurement at this depth. */
  readonly alpha: number
  /** Union area of one sixty-degree fan (equilateral, height 1). */
  readonly fanArea: number
  /** Union area of all three fans' slices together. */
  readonly sweepArea: number
  /** Total join sector area at excursion 100; scales like 1/excursion. */
  readonly joinArea: number
}

export const AREA_TABLE: readonly AreaRow[] = [
  { depth: 1, alpha: 0.65, fanArea: 0.385381, sweepArea: 0.959845, joinArea: 0.025098 },
  { depth: 2, alpha: 0.7, fanArea: 0.288791, sweepArea: 0.840391, joinArea: 0.02703 },
  { depth: 3, alpha: 0.75, fanArea: 0.23483, sweepArea: 0.698477, joinArea: 0.02778 },
  { depth: 4, alpha: 0.8, fanArea: 0.201745, sweepArea: 0.603291, joinArea: 0.027853 },
  { depth: 5, alpha: 0.8, fanArea: 0.174381, sweepArea: 0.52271, joinArea: 0.028872 },
  { depth: 6, alpha: 0.8, fanArea: 0.156868, sweepArea: 0.470499, joinArea: 0.029688 },
  { depth: 7, alpha: 0.85, fanArea: 0.142433, sweepArea: 0.427237, joinArea: 0.028905 },
  { depth: 8, alpha: 0.85, fanArea: 0.128597, sweepArea: 0.385774, joinArea: 0.029511 },
  { depth: 9, alpha: 0.85, fanArea: 0.118599, sweepArea: 0.355795, joinArea: 0.030027 },
]
